class QuickKey:
    ctrl_v = 'ctrl+v'
    ctrl_e = 'ctrl+e'
    ctrl_r = 'ctrl+r'
    ctrl_tab = 'ctrl+tab'
    ctrl_alt_tab = 'ctrl+alt+tab'
    upArrow = 'up'
    downArrow = 'down'
    rightArrow = 'right'
    leftArrow = 'left'